<?php

namespace AdminBundle\Repository;

/**
 * TableDatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableDatabaseRepository extends \Doctrine\ORM\EntityRepository
{
}
